# Generated by Django 3.2.6 on 2022-06-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCiGp1100X',
            fields=[
                ('case_key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=4, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('test_bed', models.CharField(blank=True, max_length=128, null=True)),
                ('tester', models.CharField(blank=True, max_length=45, null=True)),
                ('script', models.CharField(blank=True, max_length=256, null=True)),
                ('headline', models.CharField(blank=True, max_length=512, null=True)),
                ('log', models.CharField(blank=True, max_length=256, null=True)),
                ('runner_host', models.CharField(blank=True, max_length=45, null=True)),
                ('issue_tickets', models.CharField(blank=True, max_length=45, null=True)),
                ('ci_online', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'auto_ci_GP1100X',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoCiGs4227Xgs',
            fields=[
                ('case_key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=4, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('test_bed', models.CharField(blank=True, max_length=128, null=True)),
                ('tester', models.CharField(blank=True, max_length=45, null=True)),
                ('script', models.CharField(blank=True, max_length=256, null=True)),
                ('headline', models.CharField(blank=True, max_length=512, null=True)),
                ('log', models.CharField(blank=True, max_length=256, null=True)),
                ('runner_host', models.CharField(blank=True, max_length=45, null=True)),
                ('issue_tickets', models.CharField(blank=True, max_length=45, null=True)),
                ('ci_online', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'auto_ci_GS4227_XGS',
                'managed': False,
            },
        ),
    ]
